apiVersion: v1
kind: Service
metadata:
  name: medusa-service
  namespace: medusa-dev
  labels:
    app: medusa
    component: server
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: medusa
    component: server

---
apiVersion: v1
kind: Service
metadata:
  name: medusa-nodeport
  namespace: medusa-dev
  labels:
    app: medusa
    component: server
    environment: dev
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: medusa
    component: server